### ISSUE TITLE
Undocumented averaging protocol by summary_interval

### ISSUE THREAD

**Issue by ezwelty** [gadomski/cwms-jsonapi#4]
Are the data simply averaged by taking the mean of all values within each time interval specified by `summary_interval`? Do the associated timestamps correspond to the start (most likely), middle, or end of that time interval?

**Comment by gadomski** [comment]
> Are the data simply averaged by taking the mean of all values within each time interval specified by summary_interval?

Yes, unless `circular == "true"`, in which case [the circular average](https://github.com/gadomski/cwms-jsonapi/blob/master/U_CIRCULAR_AVG.sql#L8) is taken (e.g. for wind direction).

> Do the associated timestamps correspond to the start (most likely), middle, or end of that time interval?

Start (via the `trunc` function, https://github.com/gadomski/cwms-jsonapi/blob/master/JSONAPI.sql#L310).

/me twitches a bit looking at old PL/SQL code :nauseated_face: 

@ezwelty if you've got a moment, pull requests are welcome for documenting this stuff 😄. Otherwise I'll get to it eventually, but it's low on my chop list. Leaving this issue open until documented.

**Comment by gadomski** [comment]
Fixed by #6.

@ezwelty just FYI it looks like the `Fixes #6` text needs to be in a commit message, not just in the pull request comment. I didn't know that until just now.
